- name: install packages 
  apt:
      pkg:
      - vim
      - unattended-upgrades
      - chrony
      - mailutils
      - logwatch
      - postfix
      - prometheus-node-exporter
      update_cache: yes

- name: upgrade all packages
  apt: upgrade=dist

- name: Set up Postfix to relay mail
  debconf: name=postfix
           question='{{ item.question }}'
           value='{{ item.value }}'
           vtype='{{ item.vtype }}'
  with_items:
      - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
      - { question: 'postfix/main_mailer_type', value: 'Sattelite system', vtype: 'string' }
      - { question: 'postfix/relayhost', value: 'mx.services.ka.xcore.net', vtype: 'string' }
      - { question: 'postfix/root_address', value: 'marcel', vtype: 'string'}
  notify: Reconfigure postfix

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh

- name: Disallow root SSH acces without keys
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin without-password"
              state=present
  notify: Restart ssh 

- name: Only allow specific users from internal networks
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    line: "{{ ssh_allow_users }}"
    state: present
  notify: Restart ssh 


