- name: install packages 
  apt:
      pkg:
      - vim
      - unattended-upgrades
      - chrony
      - mailutils
      - logwatch
      - prometheus-node-exporter
      - openssh-server
      update_cache: yes

- name: upgrade all packages
  apt: upgrade=dist

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh

- name: Disallow root SSH acces without keys
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin without-password"
              state=present
  notify: Restart ssh 

- name: Only allow specific users from internal networks
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    line: "{{ ssh_allow_users }}"
    state: present
  notify: Restart ssh 

