- name: install basic-server packages 
  apt:
      pkg:
      - vim
      - unattended-upgrades
      - chrony
      - mailutils
      - logwatch
      - prometheus-node-exporter
      - openssh-server
      - net-tools
      - rsync
      state: present
      update_cache: yes

- name: upgrade all packages
  apt: upgrade=dist

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh

- name: Disallow root SSH acces without keys
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin without-password"
              state=present
  notify: Restart ssh 

- name: Only allow specific users from internal networks
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    line: "{{ ssh_allow_users }}"
    state: present
  notify: Restart ssh 

- name: does logwatch send mail to correct mailbox?
  shell: grep logwatch@xcore.net /etc/cron.daily/00logwatch
  register: logwatch_correct_email
  ignore_errors: yes

- name: copy logwatch config
  copy: 
    dest: /etc/cron.daily/00logwatch
    src: files/00logwatch
  when: logwatch_correct_email.rc > 0 

