- name: Restart ssh
  service: name=ssh state=restarted

- name: Reconfigure postfix
  command: dpkg-reconfigure -f noninteractive postfix 
  notify: Restart postfix

- name: Restart postfix 
  service: name=postfix state=restarted
