---
- name: apt-update and install basic software 
  apt: 
    pkg:
        - vim
        - zsh
        - sudo
        - birthday
        - nmap
        - git
        - fish
    update_cache: yes 

- name: change default shell of user to fish 
  user:
      name: "{{ unix_username }}"
      comment: "{{ unix_user_gecos }}"
      groups: sudo
      append: yes
      shell: /usr/bin/fish
      state: present

- name: clone config files
  git: "repo=https://github.com/NeoLeMarc/config-files version=master dest=/home/{{ unix_username }}/config-files"
  become: yes
  become_user: "{{ unix_username }}"

- name: get latest version of oh-my-zsh
  git: "repo=https://github.com/ohmyzsh/ohmyzsh.git version=master dest=/home/{{ unix_username }}/.oh-my-zsh"
  become: yes
  become_user: "{{ unix_username }}"

- name: create fish config dir
  file:
      path: "/home/{{ unix_username }}/.config/fish"
      state: directory
      recurse: yes
      owner: marcel
      group: marcel
      mode: '0750'

- name: link fish config for user 
  file:
      src: "/home/{{ unix_username }}/config-files/config.fish"
      dest: "/home/{{ unix_username }}/.config/fish/config.fish"
      owner: "{{ unix_username }}"
      group: "{{ unix_username }}"
      state: link

- name: link zshrc for user 
  file:
      src: "/home/{{ unix_username }}/config-files/zshrc"
      dest: "/home/{{ unix_username }}/.zshrc"
      owner: "{{ unix_username }}"
      group: "{{ unix_username }}"
      state: link

- name: link vimrc for user 
  file:
      src: "/home/{{ unix_username }}/config-files/vimrc"
      dest: "/home/{{ unix_username }}/.vimrc"
      owner: "{{ unix_username }}"
      group: "{{ unix_username }}" 
      state: link

- name: link exrc for user
  file:
      src: "/home/{{ unix_username }}/config-files/exrc"
      dest: "/home/{{ unix_username }}/.exrc"
      owner: "{{ unix_username }}"
      group: "{{ unix_username }}"
      state: link

- name: add authorized keys
  authorized_key:
      user: "{{ unix_username }}"
      state: present
      key: "{{ unix_user_ssh_keyfile }}"
