---
- name: ensure postfix package is installed
  apt:
    pkg:
      - postfix

- name: Set up Postfix to relay mail
  debconf: name=postfix
           question='{{ item.question }}'
           value='{{ item.value }}'
           vtype='{{ item.vtype }}'
  with_items:
      - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
      - { question: 'postfix/main_mailer_type', value: 'Sattelite system', vtype: 'string' }
      - { question: 'postfix/relayhost', value: 'mx.services.ka.xcore.net', vtype: 'string' }
      - { question: 'postfix/root_address', value: 'marcel', vtype: 'string'}
  notify: Reconfigure postfix


